### ISSUE TITLE
school profile bug

### ISSUE THREAD

**Issue by mikelmaron** [mapkibera/map-kibera-schools#13]
When you look at schools profile page, side by side, highlights number of students at the top of the OpenDataKenya column but not MK column. 

I think it’s good to highlight that stat; not sure if the contrast needs to be highlighted but it seems odd as is now. Unclear if you’ve already changed this page so as to make this point moot.

**Comment by uniphil** [comment]
@mikelmaron could you clarify this for me please?

Is this issue visible on staging? http://kibera-schools.dgstg.org/schools/1771323210/akili-complex/

> Unclear if you’ve already changed this page so as to make this point moot.

is that referring to me?

**Comment by mikelmaron** [comment]
Not sure, who this referred to, was a while ago :)

Prior versions of the school profile page had highlighted stats, but no longer. Guess they went missing at some point. I'm going to make this medium priority, while I figure out what specifically should be there.

**Comment by bcarancibia** [comment]
The highlighted section was removed because of a design request during the last round of design changes.
