### ISSUE TITLE
Make photo layout 3 wide. Link to larger photos

### ISSUE THREAD

**Issue by mikelmaron** [mapkibera/map-kibera-schools#21]
On school profile page, make three photos wide. Click on photo should open larger in popover or other window.

**Comment by uniphil** [comment]
@mikelmaron , there are not any larger photos in the datase, so it still links to the thumbnail image (in a new tab now though).

**Comment by mikelmaron** [comment]
right, exactly. i'm creating those now and will link in

**Comment by mikelmaron** [comment]
ok done https://github.com/mapkibera/map-kibera-schools/commit/da4ebca6423d38b63bfba7af3fa6c69861c98e4e
