### ISSUE TITLE
possibly remove "highlights"

### ISSUE THREAD

**Issue by mikelmaron** [mapkibera/map-kibera-schools#22]
“highlights” top menu selector is useless - IMO, just scrolls you down to where you already will go. May as well remove unless has other intended purpose.

**Comment by mikelmaron** [comment]
Needs decision by @ericahagen

**Comment by mikelmaron** [comment]
going to keep it

**Comment by ericahagen** [comment]
problem is really, these are actions.

means they make more sense without the video header. which is orig design

but we’ve screwewd with that.

if we get to gen2 we’ll re think , perhaps.



Erica Hagen 
www.groundtruth.in <http://www.groundtruthinitiative.org/>
+1 773 313 5782

mapkibera.org <http://mapkibera.org/>
