### ISSUE TITLE
Click "Compare" on School profile, jumps down

### ISSUE THREAD

**Issue by mikelmaron** [mapkibera/map-kibera-schools#35]
Other buttons don't cause a jump. Can we get this behavior on the Compare button?

**Comment by uniphil** [comment]
hey @mikelmaron, sorry I didn't get to these over the weekend, and awesome that you got them yourself :) it all looks great.

a quick github note: when you make a commit that is related to a github issue, if you put the issue number anywhere in the commit message (like "fixes #35"), github will link the commit to the issue and this issue to the commit, which makes it easy to see why changes were made to the code, and what code changes fixed which issue.

**Comment by mikelmaron** [comment]
yup, figured out how to fix. 
know about issue linking, was just kinda both lazy!
For reference, here's the relevant commit
https://github.com/mapkibera/map-kibera-schools/commit/2cd9a1d96acd17c0ad4554c52421a4e93fcacc34
   * Mikel Maron * +14152835207 @mikel s:mikelmaron 

     On Monday, February 23, 2015 9:30 AM, phil <notifications@github.com> wrote:
   
 

 hey @mikelmaron, sorry I didn't get to these over the weekend, and awesome that you got them yourself :) it all looks great.a quick github note: when you make a commit that is related to a github issue, if you put the issue number anywhere in the commit message (like "fixes #35"), github will link the commit to the issue and this issue to the commit, which makes it easy to see why changes were made to the code, and what code changes fixed which issue.—

**Comment by uniphil** [comment]
:+1:
