### ISSUE TITLE
auto slide featured things

### ISSUE THREAD

**Issue by mikelmaron** [mapkibera/map-kibera-schools#42]

**Comment by uniphil** [comment]
Unless there is a compelling reason to add this, I would suggest not. I can dig up the research if you want, but there are user studies showing that people block out animated sliders almost completely, as if they were ads. It's considerred an anti-pattern.

Maybe some left/right buttons, like on the school profile pages photos, could be added to make rotating through them a little easier?

**Comment by mikelmaron** [comment]
Good point Phil, I agree. It just needs to be more obvious that you can rotate through. left/right buttons would work. * Mikel Maron * +14152835207 @mikel s:mikelmaron 

     On Monday, February 23, 2015 9:06 AM, phil <notifications@github.com> wrote:
   
 

 Unless there is a compelling reason to add this, I would suggest not. I can dig up the research if you want, but there are user studies showing that people block out animated sliders almost completely, as if they were ads. It's considerred an anti-pattern.Maybe some left/right buttons, like on the school profile pages photos, could be added to make rotating through them a little easier?—

**Comment by mikelmaron** [comment]
@uniphil, the left / right buttons aren't working on the image slider either. any suggestion?
