### ISSUE TITLE
Add Kangemi to Location drop down

### ISSUE THREAD

**Issue by mikelmaron** [mapkibera/map-kibera-schools#87]

**Comment by mikelmaron** [comment]
need boundary from Zach. will filter schools on that and add as an option

**Comment by ericahagen** [comment]
Mikel - what boundary do you still need?

**Comment by ericahagen** [comment]
Hey
I have resend the boundaries for both Kangemi and Mountain view plus the
boujding box of the area that we mapped.

Zacharia Muindi
Lead Mapper
Map Kibera Trust| www.mapkibera.org | www.openschoolskenya.org
+254(0)716610114| +254(0)736202692
Twitter: @muindre
Skype: Zacharia Muindi

**Comment by mikelmaron** [comment]
added!
