### ISSUE TITLE
Toilet data missing on OSK

### ISSUE THREAD

**Issue by muindre** [mapkibera/map-kibera-schools#97]
@mikelmaron I noticed that toilets data is not appearing on OSK yet the data is OSM
Here is an example of one of the schools http://openschoolskenya.org/schools/5948174099/shani-taji-school/ 
https://www.openstreetmap.org/node/5948174099/history.

Is it possible to have this fixed before thursday.

**Comment by mikelmaron** [comment]
Had to update the configuration for tag matching (we weren't mapping this before in OSM)

Does this now look resolved @muindre ?
